############################################################
@local = https://localhost:6999
@deploy = https://

############################################################
### local test requests
POST {{local}}/addClientToServe
content-type: application/json

{
    "clientPublicKey": "...", 
    "timestamp": "...", 
    "signature": "..."
}

### 
POST {{local}}/getNodeId
content-type: application/json

{
    "clientPublicKey": "...", 
    "timestamp": "...", 
    "signature": "..."
}

### 
POST {{local}}/startSession
content-type: application/json

{
    "clientPublicKey": "...", 
    "timestamp": "...", 
    "signature": "..."
}

### 
POST {{local}}/startSession
content-type: application/json

{
    "clientPublicKey": "...", 
    "timestamp": "...", 
    "signature": "..."
}




############################################################
### deployment requests
POST {{deploy}}/route
content-type: application/json

{
}